services:
  - type: web
    name: ghostmodzz-flow-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
