services:
  - type: web
    name: ghostmodzz-flow-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade &&
      gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
